version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: db-back
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 33063:3306
    environment:
      - MYSQL_ROOT_PASSWORD=c@r123
      - MYSQL_DATABASE=car-user-system
    volumes:
      - db-car-user-system:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  db-car-user-system:
