pipeline {
    agent any

    environment {
        SONARQUBE_URL = 'http://sonarqube:9000'
    }

    stages {
        stage('Build Backend') {
            steps {
                dir('car-user-system/discovery') {
                    sh 'mvn clean package'
                }
                dir('car-user-system/gateway') {
                    sh 'mvn clean package'
                }
                dir('car-user-system/auth') {
                    sh 'mvn clean package'
                }                                
                dir('car-user-system/back-end') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('front-car-user-system') {
                    sh 'npm install'
                    sh 'npm run build --prod'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    dir('car-user-system/back-end') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                script {
                    sh 'docker-compose build'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'docker-compose up -d'
                }
            }
        }
    }
}
